remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Code For A Cause
description: We are a group of Staples High School students who are passionate about technology and want to make a difference in the world.