remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Code For A Cause
description: At Staples High School. We are a group of students who are passionate about technology and want to make a difference in the world.